<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoryCourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('category_course')->insert([
            array('course_id' => '1','category_id' => '1'),
            array('course_id' => '2','category_id' => '1'),
            array('course_id' => '3','category_id' => '1'),
            array('course_id' => '4','category_id' => '1'),
            array('course_id' => '5','category_id' => '1'),
            array('course_id' => '6','category_id' => '1'),
            array('course_id' => '7','category_id' => '1'),
            array('course_id' => '8','category_id' => '1'),
            array('course_id' => '9','category_id' => '1'),
            array('course_id' => '10','category_id' => '1'),
            array('course_id' => '11','category_id' => '1'),
            array('course_id' => '12','category_id' => '1'),
            array('course_id' => '13','category_id' => '1'),
            array('course_id' => '14','category_id' => '1'),
            array('course_id' => '15','category_id' => '1'),
            array('course_id' => '16','category_id' => '1'),
            array('course_id' => '17','category_id' => '1'),
            array('course_id' => '18','category_id' => '1'),
            array('course_id' => '19','category_id' => '1'),
            array('course_id' => '20','category_id' => '1'),
            array('course_id' => '21','category_id' => '1'),
            array('course_id' => '22','category_id' => '1'),
            array('course_id' => '23','category_id' => '1'),
            array('course_id' => '24','category_id' => '1'),
            array('course_id' => '25','category_id' => '1'),
            array('course_id' => '26','category_id' => '1'),
            array('course_id' => '27','category_id' => '1'),
            array('course_id' => '28','category_id' => '1'),
            array('course_id' => '29','category_id' => '1'),
            array('course_id' => '30','category_id' => '1'),
            array('course_id' => '52','category_id' => '2'),
            array('course_id' => '53','category_id' => '2'),
            array('course_id' => '54','category_id' => '2'),
            array('course_id' => '55','category_id' => '2'),
            array('course_id' => '56','category_id' => '2'),
            array('course_id' => '57','category_id' => '2'),
            array('course_id' => '58','category_id' => '2'),
            array('course_id' => '59','category_id' => '2'),
            array('course_id' => '60','category_id' => '2'),
            array('course_id' => '61','category_id' => '2'),
            array('course_id' => '62','category_id' => '2'),
            array('course_id' => '63','category_id' => '2'),
            array('course_id' => '64','category_id' => '2'),
            array('course_id' => '65','category_id' => '2'),
            array('course_id' => '66','category_id' => '2'),
            array('course_id' => '67','category_id' => '2'),
            array('course_id' => '68','category_id' => '2'),
            array('course_id' => '69','category_id' => '2'),
            array('course_id' => '70','category_id' => '2'),
            array('course_id' => '71','category_id' => '2'),
            array('course_id' => '72','category_id' => '2'),
            array('course_id' => '73','category_id' => '2'),
            array('course_id' => '74','category_id' => '2'),
            array('course_id' => '75','category_id' => '2'),
            array('course_id' => '76','category_id' => '2'),
            array('course_id' => '77','category_id' => '2'),
            array('course_id' => '78','category_id' => '2'),
            array('course_id' => '79','category_id' => '2'),
            array('course_id' => '80','category_id' => '2'),
            array('course_id' => '81','category_id' => '2'),
            array('course_id' => '113','category_id' => '3'),
            array('course_id' => '114','category_id' => '3'),
            array('course_id' => '115','category_id' => '3'),
            array('course_id' => '116','category_id' => '3'),
            array('course_id' => '117','category_id' => '3'),
            array('course_id' => '118','category_id' => '3'),
            array('course_id' => '119','category_id' => '3'),
            array('course_id' => '120','category_id' => '3'),
            array('course_id' => '121','category_id' => '3'),
            array('course_id' => '122','category_id' => '3'),
            array('course_id' => '123','category_id' => '3'),
            array('course_id' => '124','category_id' => '3'),
            array('course_id' => '125','category_id' => '3'),
            array('course_id' => '126','category_id' => '3'),
            array('course_id' => '127','category_id' => '3'),
            array('course_id' => '128','category_id' => '3'),
            array('course_id' => '129','category_id' => '3'),
            array('course_id' => '130','category_id' => '3'),
            array('course_id' => '131','category_id' => '3'),
            array('course_id' => '132','category_id' => '3'),
            array('course_id' => '133','category_id' => '3'),
            array('course_id' => '134','category_id' => '3'),
            array('course_id' => '135','category_id' => '3'),
            array('course_id' => '136','category_id' => '3'),
            array('course_id' => '137','category_id' => '3'),
            array('course_id' => '138','category_id' => '3'),
            array('course_id' => '139','category_id' => '3'),
            array('course_id' => '140','category_id' => '3'),
            array('course_id' => '141','category_id' => '3'),
            array('course_id' => '142','category_id' => '3'),
            array('course_id' => '168','category_id' => '4'),
            array('course_id' => '170','category_id' => '4'),
            array('course_id' => '171','category_id' => '4'),
            array('course_id' => '172','category_id' => '4'),
            array('course_id' => '173','category_id' => '4'),
            array('course_id' => '168','category_id' => '4'),
            array('course_id' => '169','category_id' => '4')
        ]);
    }
}
