language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_script:
  - mysql -e 'create database cityuge;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
