version: '2'

services:
    cityuge:
        build: .
        volumes:
            - ./:/var/www/html
        ports:
            - "3000:80"
        container_name: cityuge
    mysql:
        image: mysql:5.6.33
        restart: on-failure:20
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - "./${CLUSTER}/mysql/db2:/var/lib/mysql"
            - "./${CLUSTER}/mysql/conf:/etc/mysql/conf.d"
        ports:
            - "3306:3306"
        container_name: cityuge-mysql
